global:
  resolve_timeout: 5m

# Route configuration
route:
  receiver: 'telegram-webhook'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

# Receiver configuration
receivers:
  - name: 'telegram-webhook'
    webhook_configs:
      - url: 'http://192.168.1.104:8001/webhook/alerts'
        send_resolved: true
        http_config:
          follow_redirects: true
        max_alerts: 0

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
